name: Build Dynamic Delay - Windows
run-name: "Windows build: Dynamic Stream Delay 🎮"
on:
  workflow_dispatch:
    inputs:
      config:
        description: Build configuration
        required: false
        default: RelWithDebInfo
        type: choice
        options:
          - RelWithDebInfo
          - Release
          - Debug

permissions:
  contents: read

jobs:
  windows-build:
    name: Windows x64 🪟
    runs-on: windows-2025-vs2026
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build OBS Studio 🧱
        uses: ./.github/actions/build-obs
        with:
          target: x64
          config: ${{ inputs.config }}

      - name: Package OBS Studio 📀
        uses: ./.github/actions/package-obs
        with:
          target: x64
          config: ${{ inputs.config }}
          package: 'true'

      - name: Upload Artifact 📡
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: obs-studio-dynamic-delay-windows-x64
          path: ${{ github.workspace }}/build_x64/obs-studio-*-windows-x64.zip
          retention-days: 7
